
services:

  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "${PORT}:${PORT}"
    env_file: '.env'
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - shared_network
    command: yarn run start:dev

  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_network

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    env_file: '.env'
    networks:
      - shared_network

volumes:
  pgdata:

networks:
  shared_network:
    driver: bridge
