
services:

  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - "${PORT}:3000"
    env_file: '.env'
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - shared_network
    command: yarn run start:dev

  db:
    container_name: db
    image: postgres:16-alpine
    restart: always
    env_file: '.env'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  pgdata:

networks:
  shared_network:
