apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: client
      labels:
        tier: frontend
    spec:
      containers:
        - name: client
          image: googlevlad/easypay-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          command: [ "npm", "run", "start" ]
          args: ["--env-file=.env"]
          resources:
            requests:
              cpu: "500m"