apiVersion: v1
kind: Service
metadata:
  name: backend-internal-lb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.1.0.20
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: 'Local'
  loadBalancerSourceRanges:
    - 10.1.0.0/16
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    tier: backend

