apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: easypay-dev
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    tier: frontend