apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "rg-easypay-rare-oarfishn"
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "20.186.10.39"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    tier: frontend